package contextmenu

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/Lekuruu/go-puush-client/internal/desktop"
)

const (
	menuLabel       = "Upload with puush"
	ownershipMarker = "Generated by puush"
)

var (
	ErrDevelopmentBuild    = errors.New("context menus are not supported for temporary development builds")
	ErrUnsupportedPlatform = errors.New("context menus are not supported on this platform")
)

// Apply installs / removes the context menu integration for the current user.
func Apply(enabled bool) error {
	executable, err := os.Executable()
	if err != nil {
		return fmt.Errorf("find puush executable: %w", err)
	}
	executable, err = filepath.Abs(executable)
	if err != nil {
		return fmt.Errorf("resolve puush executable: %w", err)
	}

	if enabled && desktop.IsDevelopmentBuild(executable) {
		// We don't want to apply context menu's for dev builds
		return ErrDevelopmentBuild
	}
	return applyPlatform(filepath.Clean(executable), enabled)
}
