package contextmenu

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	menuLabel       = "Upload with puush"
	ownershipMarker = "Generated by puush"
)

var (
	ErrDevelopmentBuild    = errors.New("context menus are not supported for temporary development builds")
	ErrUnsupportedPlatform = errors.New("context menus are not supported on this platform")
)

// Apply installs / removes the context menu integration for the current user.
func Apply(enabled bool) error {
	executable, err := os.Executable()
	if err != nil {
		return fmt.Errorf("find puush executable: %w", err)
	}
	executable, err = filepath.Abs(executable)
	if err != nil {
		return fmt.Errorf("resolve puush executable: %w", err)
	}

	if enabled && isTemporaryDevelopmentBuild(executable) {
		// We don't want to apply context menu's for dev builds
		return ErrDevelopmentBuild
	}
	return applyPlatform(filepath.Clean(executable), enabled)
}

func isTemporaryDevelopmentBuild(executable string) bool {
	base := filepath.Base(executable)
	isDesktopBinary := base == "desktop" || strings.EqualFold(base, "desktop.exe") // TODO: eventually I want to rename the binary to "puush"
	return isDesktopBinary && strings.Contains(executable, "go-build")
}
